services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cafe.db:/app/cafe.db
      - ./log.txt:/app/log.txt
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    restart: always
