services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pos.db:/app/pos.db
      - ./log.txt:/app/log.txt
    env_file:
      - .env
    restart: always

  frontend:
    build: ../pos-frontend
    ports:
      - "5173:3000"
    restart: always
